apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-payment
  namespace: airbnb
spec:
  imagePullSecrets:
  - name: ghcr-pull-secret
  replicas: 1
  selector:
    matchLabels:
      app: service-payment
  template:
    metadata:
      labels:
        app: service-payment
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: service-payment
          image: ghcr.io/my-airbnb/service-payment:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-payment-config
            - secretRef:
                name: service-payment-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
