# TEMPLATE - seal with kubeseal
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-payment-secret
  namespace: airbnb
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: <SEALED>
    JWT_SECRET: <SEALED>
    STRIPE_SECRET_KEY: <SEALED>
    STRIPE_WEBHOOK_SECRET: <SEALED>
