apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-guidebook-hpa
  namespace: airbnb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-guidebook
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
