---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-guidebook-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCGIGEZVI49bYxfIXioJw85JLkGrmFuju9CeuvvFkUFBJcMN6bRvIrVTjhe0UvUCBZHXbXt/kzGKuiaWPKLMwxbAV3RqBHRZ8ojly1Cb6+NH8rO+IjB2GFXuKS/mv/MD8U/s0q0UGfqZLuK+tS6cKq16uCO0C3lZ9M1sUKDI9aiWWcMA5rnEWcffdVd06vsoE/ob8x7pnL9+WUcg6NIGj4p76vw2VdEI7+SIKEq2sMmBYJ/kMuiD/U1ZjzjU7mQ2VykkEl2FuDNfJrX8AjO8c6ipWEE5Ug8rgXbV/se30pfVZiFQ0m6L9RNJW8FyhR3IaSVqOUCFXw0vOVnbhXID5W+k/HMqA+imAmHY11inYS74nT+8iqib/TFXfiOuFBY4ywSvKsRcW3OolfoEESuFfYL9gdgr8I8+l+7MW6uppaTuygg8GMhRfDc/6m1AWBNvBQvpCbvTZGP+v46oYWC7jtcUyNwqCGhiWewbjaVCl+Rpq400XJSwfzv+EPZNk908Uf47v+H0zye9s7NQWEzMG9rfHIKwVUA0wvSfroLAwziFisXFY8Il4R/Wmoxl+iCIuCIbDbJvSVy0FYeNxq6ykDkvi3lCO8ESkt51tcxPlbUsZKkIsKeXUK3JPYlT9xFQodY+zM4lvxVwiANC95eStkRMTgVyUnBGwcaha71Rn7xYcnU+icHTn3SedKIzFfOMJ/iPCEFOniwljGokHqHcdXCIbtDmgGRWD+gxmQxEDAh3MywrCntAVpVT2W2JC7F/S1sPtYxSELAa1o6c3tjYSmJ0CcoNvalDSDCPS8ZNA1qpA/mq+aSy2TQdVbjW9A9hlGI6XkmKbNTT+2uFKXC5oz5iMlNo/ZT+LgVfNO6tGKpLw==
  template:
    metadata:
      creationTimestamp: null
      name: service-guidebook-secret
      namespace: airbnb
