---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neo4j-secret
  namespace: airbnb
spec:
  encryptedData:
    NEO4J_AUTH: AgCibqbRt3zXyrVCJntyPmdCRfz2rWRRPlgIMcvf+ca4cyNDU31VAmzqRHcOsKPE1xnRPx61UyuYwWmrizLYdv8hGQ36UuWR2ve1IpGymuPU+Q7eMFHqfB2Ow3872EAUi82UimzH3OEwxy3cHdcLzcDJejJqJ6x8yV2zEZwq4bAOGczpl9nN+97MQa4WkmS4h1UGL084NVlloPE7a6LdTW1ypQN/rkbMV59hCUIhNM8VUTdaLltlwXLJefIYOBVu4lS/PBQ6dWJmLB/Z5cgC2YDO9HaAkV/Z2oxt6AKh/WFytDaK7vSPMUxqEBUV9gvG3ecfd8GZ5d0ldsfOjY337eMUkeIaih4Nc0chvwqfz5kzCb4yhkPSsLg+w10eYUQ0lmort4rtrwwg0JTYN/r8oUQz2f4ZweNNhYjCSke8UAykZHqiYeNIGydYZz3UeHby2sKtYsk8+SQ2Sa0CAMHyejhIKyh5KjJZOh6ZH/WpNfHqTAS1+w1sJqi8eHGCmUoA7ZX8/MtptpM67WzVngIu5GwzS/Ku3gj7IFMIOSf0Oq+wG+fzhYQooI51xe4HCI3Nak0jAEAusuCeFflK8eIaEdi2bpX0S1mYh8iHvuSWlJ2HRCTe3ct7h0nKUfBx0UHD9oECYYLmqeb0b0PWHjB9wzq/pTS77Qu5xqkyoCeo8t2PQ5GscsA3KoxxGsRQvyk5+YvYMgJGTSqsN/ed/BLXB3IqjHKAdu6ahKKlUg==
  template:
    metadata:
      creationTimestamp: null
      name: neo4j-secret
      namespace: airbnb
