apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: airbnb
data:
  NEXT_PUBLIC_API_URL: "/api/v1"
  NODE_ENV: "production"
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
  MINIO_PUBLIC_URL: "https://airbb.serghini.me/storage"
  LISTING_SERVICE_URL: "http://service-listing:8082"
  REVIEW_SERVICE_URL: "http://service-review:8086"
  SUGGESTION_SERVICE_URL: "http://service-suggestion:8087"
