apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: frontend
          image: ghcr.io/my-airbnb/frontend:dev-70c2901e30998cd4eb8c7426d5d3350d0062742a
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: next-cache
              mountPath: /app/.next/cache
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: next-cache
          persistentVolumeClaim:
            claimName: frontend-next-cache
