# TEMPLATE - seal with kubeseal
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secret
  namespace: airbnb
spec:
  encryptedData:
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: <SEALED>
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: <SEALED>
    NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: <SEALED>
