---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-wishlist-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgB2GWUY2zCPyE0eu6p9dz8XJttMMEHSxhQnP0+YKA2LMaeSChBHZ9uk2xPatp8JAxbZ1OO87f1KinSccgcIsKmtBQ90jxAycM2vgD/tL6pAlhuaXn/fPl+K2eL41fVNldRpYixoBeYsUuyuv5Vq3cvJO/1y1CGGhpW0jpwZLX56kc6ItRAsN1++MvdxsxfD1cC4ztHhTAwI5lmihxMOFeAprus9jOjPDDGx/zWbVwUlALJNO6S0g3Bl6vNyYXCxGhuAfTPnzT1kQpib9pgbIFNbR5H6/2JVaUWYcXvGd4MXjlszx+MEtq5T47kfyyEE9EJ7RSI4P6pkEhTW/AiOfRHtrmi0nHG7DPBl/YTGLO+f3JIooZxY/fW2ZegglB+qDXdHPn9ndtg7rBXk3ViMUEPIM8vihKD/udb+62VsUcxESisVT0a1GWXyjVjblUHaLn4UCR+k2TLvtK5kaWV03XY+5sz48S1EWiXC0tKhVJXKIOx1SeG4e5yZqhf881KIWhQdOKToQOEsNPiQBHiTADOGi9feviF6w0GuZMewEKa4iYulllzcG9qifSNXm0LYG2Q8QBXLzRy1H9liWYKaDADvbw1dLQ1B6ZXCIyazjRHrRYu9VKV8+UohAQx7ggu4mZldCwr2KSUZsw15ssOhknsBiB5fCXV15vYYPMsFzR5oBHkVm2Q3VAOyZx14V1fdZZOyDZ0IPfiV6ktqWmL8LCitvDrTNXoc5Sq/lncgR7SIhRBb0qYK0KsvVb3qYK7aVTNDHWorweane2p5QNLbbEQpf6/kGSWv/yXW063NuWa35W+7O29kpQs15JbvGWm8g7iq8A9Ao4yJJV9AyT8OYiigrpvHCAxzX6Q7Tgl9Jq3lug==
  template:
    metadata:
      creationTimestamp: null
      name: service-wishlist-secret
      namespace: airbnb
