apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
  namespace: airbnb
data:
  01-create-users.js: |
    db = db.getSiblingDB('admin');
    db.createUser({
      user: 'mongo_user',
      pwd: 'CHANGE_ME',
      roles: [
        { role: 'readWrite', db: 'listing_db' },
        { role: 'readWrite', db: 'chat_db' },
        { role: 'readWrite', db: 'notification_db' },
        { role: 'readWrite', db: 'wishlist_db' },
        { role: 'readWrite', db: 'availability_db' },
        { role: 'readWrite', db: 'recentlyviewed_db' },
        { role: 'readWrite', db: 'guidebook_db' },
        { role: 'readWrite', db: 'coupon_db' },
        { role: 'readWrite', db: 'qa_db' }
      ]
    });
