---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: airbnb
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgA2hUbVijyyYdmmAfJO9odLC+VtnkiTgIfK55BE5HfHn2PEePJc+eKkFry831aIW7ASmGBUwRNO6tZu3inmn8pRJmXhy7/3Y0wof2OYbUujcoO1zfd3iTpIiNU+hLV6ITMhEFy7+c6AlPnZtxtHw+ebva416Num68cMuT3NuHRHvoCfFJf/s5K0xWl77egH0F7ubO9a6yW7D/EYHLZIhW1pGzY5LL/+c3MsQd7WcX8fejIl7aBJpvdO46/FW3pBnYSdSjoMw87DJa3jnfFdXRD6mO2vAqvha+teD8Epa087f1vU1uvDsYZkGjp+5pWM2r/KuNgM/pwH4sx1bHRGk4aJLd62mJQNp5Fch3Q0PbbjdmgQ6v1mBFnQgdZdmBgwhKwd4zFR1MZpagJlZlVZFdiFw4lf51RQ555fy8UUup5EBLDMOiYiIMyXgGM9g/4AW3sy4AooNvW3SgSiF/3P+s0/6X0lqsX/RsMP3TactXqiC64NJ+dhaEwrjwEbKmpfVw39dN8zQOS8mFeCqugX2BpHwBka4IqVvEVReqmwjLd6cY8lgVcdnJGGupD/hoES2CbKSsqRmWzW2TQKcVEiyyIRs79W7xSYGqJw6hBIBcxFA93LNzVVAylEY+Y9o24Gc87oU0WjhdiMaBRaKguRkRORAkf/6O1FeoMGC5C4UsD9hhOa4ctu1ilBELL9m6XGFEe3HhTt9wUxUTk=
    MONGO_INITDB_ROOT_USERNAME: AgAUI/mbQsZHEoVwhPzJGKAIwWMv4CL4RAb+qBWnThlg2VcF1u8K0XDzwq7m8S8s47snfhDr1w9MoVDePW98UyphCV6Dxpm4uoAZ/aCGAQ2+M8IDeN6aSh0U8a2tGHP3ZzfYNQq3JLMRXI3kb6mr26OZtzLieFu41rrEWyIXekEJWLs8vA+fV/NgC0xcNtABhGQM7r57LKQHrA0cE2WD8qgJDXiZ259b/1ig7+KsWRUdM/KHWi8PO0xg4jy4ptx6jyZ4LFXC7eT2Dtiq+Pmt3dXv4qYiefRliiCQq/SToeJ8WrqqhUQILQPxziVyctqha5SgQU9jz+4SjBGtSoLrPfg7Lo9dUK4Ctr707eBHGPC9mniyNai32drxGmC/Ji+RnGlE5U7SeQhIbb9FX6nY1uQyH/cLGNaWWIiHX3cPjeWuNVp3GocruI5DFBBVHdLxqLJ8cw3uOH637zufFIXPS3bDb8h5VBonpyQho96xLEIgkLCYaS33HJ3L6NrR2an4qpl6B17qRYmAxdeB96DV/Ceq3mLymfpEmpq4LhHawr8BkbjsgyVqY2cMr7+/nkgqlIgZImNcfF7E2aK5eiIWrsdzNHrOKfcU5errS2V0sO6NjxW1h0X+Q8fvd6XLPzkM8ICc947qOnQ3WmelWAtwpjIe7oMwR8iGDIEuvvz+/OMJl1+OZmIYpY3XbgtpNSqv/J1DKrkc4qo=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: airbnb
