apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: airbnb
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAUGjfgnqhH3HJ+SkNRZkvBnaZhtfvWaS4FI+dmOHMCCqe3lMGkQ80tuZGAyhCL3aTrSu543TVD/ZrhIB95oOwZt6f6PgneYtGy+SlCXNMG5inQaVoDTtXvF9BPT+dMIuvX+X6ReM+R9zbFMWuv3NQfLjNuxa/UNqDDZ3fhxlkq4DrudoJO1ajLHhERaCgqK8eiQRlc+VVVupVgYuwDkRQGkdsvk9/m9HGI4Wag+hnIuetzR29oDIH4kw3qXLIaV/p5EHYLFqNq6fEzQZyo2dSgXr1fC06dbqyMz83NN4FJFh/Nk1wwH4duYMJL+BYBCFSaQO6LPa1x/7S9v2wjXj1NjchVymy7siX6Z8PokEXjJbVdHW9eJzK75b/qGp7WiD6uXYbKBzt1KYUaXu7649sFXI+c9xb8QgAQp7+hfGa6ZW8J1iQHZZtLNu1EcGwzFjjEYr7/mhvv5SL/3Zmot5FDKDKIA1dtEL/Dwx0u4NziKM2XCrRL3XmfReLaQyalVKf7iPnGtgMOdJcF9ZXW1zsopnpfSNIrXqIhX6bVr4W7w0zLVh0rdJUQlB/mm7QKb8SFzgWQt6W/6OENu21VCMujoUlbvyksYBp8H+RUBD2AMy3NDK62IWk2O6GDW7km1jDam+G6kj3ppN/QfIlX6ASo9vs7sgSNJhbfSKOe57P6ZUdNaLTRFwIU6PFxAcUv9wp+r7zN0GKzgQ==
    MONGO_INITDB_ROOT_USERNAME: AgAyY0hMUVUhRIBVK3OhHNqZ9IytHbPis3IHm3Ymm2hgml4dnIKbd6way2IGIDBL12MNiN0eZTyt9U48kNZP62jmeEgn+kmTwlv+KuBqpK6xLx8ZMLeqDstK2oFpzLkVM7LWLVy2Z5cHQShLlgMwPU5Lk8zJlEqZoKJL+QlcyN6oCmW9BYAsSAdEfkI9zr9t1bwZH1hum7lJEVxvdvAhsc+RJJCJ6WBTdi2a8Y4cGyf/PUHfzH6HgKc+mWgJB0ZPOIAL11C5O3jdCEXXYX6FALVSWvNOrKKP2gAcxUnHcsFc6fbMtf19kCFUPWI5IYODf4K+NieXYkw8yMGZJHI72ApeUW+fE9yqKPY0T9gU/aA+LVfTb+Ui4Xb1YTF0tN/1kP6iKHE8TW6/zFu7FhNnEgR/NbA5adGNjV0bQoCJtuH18+3BE+UxUSU5NOOId+wt0WmZVLFb5VJI6PZDBCtFw6qsd0SMz2+Q+IgAG2CMHtoP9Qvfc19Mnxckh3z7Pq9ZF08aPZjXs8DL+ft5PoZdAyh1BQQs2jQsIAyizfOwZ19nGinBmApc7SCmO6hEUTFuyqXqNEWE7VHYeJ8z467XDIZSFZIiwNOcEd8LFbhLd61kS9H2zSUDO8/ifvG5XPyYgj32182IeVsHdIZ4oLyz1qBWUFsrTcTOh05ijONwjuF/sDM/41A3Lb54/KuGNql6HeZnp30Jvfk=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: airbnb
    type: Opaque
