---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: airbnb
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBHbskoUvc4ziTpOVIJp8mMJACKbdY+XJJAJJCHEnNYF44e2PEuYdKfRAN4/PZj+dY1BneySXzStbGB1SW26zMVsWmVdAoxg+2CPgyRYwAzPGVom/nSJKw9S3dkvbi3MVSoFCXm9otllsKbf1x6Ua0iHA4Nf1Ws9kl5ZHCiBn/kPSzB17droY1DU2PEBugggOkb+A4VvvFhJzDwBRr2ryeDxoabvm8LzCVpfjwt31KFFkJwwP5069M6J2bktlDixBFAJwa0QCvZhwUD9E3X8eCe8K7M1DGlQV3Oby+SFApL/n2T26Qv7l5W74zaAoDwrQ/3yRqhpC34AwBFAUnBpzhI0WiiXf1ZRkwIk3grHn8NG9HMHS9q8eYFVEdbKn64JJf/AQmo1/zxTeOBDzVZ9lsAf2qZ3hTBNNkYBWUW/xRX5pYRxvMmIWUAbrOZpGI+ileoDW94+yDTZx3J+F8SYZF+j4pqC1rbwwd6IOMiDopqb1bHgR6SKLrSFRMZGWoK8Tg/icCQPENA/rCNWZIcikgKjuxSzLyIOefGJ5r6RHAwkaVSeTOluYcIOtsyy3t++0YfM5AE7lCUT8raL7GWb+JazhYaxm9YQwqQgVfI5w2LbdZXav8RF7dBMqqGjwMxzTW5gPs8UFK+SDGiQ9URimvBnCrODR82B1r8cQBt+so9zkNyI0yhStttXAWimIUxmBqLXtkl1L8rEY0=
    POSTGRES_USER: AgBiJ0ylenjZ5O5Cy4dROl5CPYnVfK+oEqGJ+smOKoqCOgxzFbjmr3kzHxVkBYWk/MYb4EDDcVbqTW4DiEsXp6cQLVauCyR6dk/Oqdj0OhWnlST0Mphn9LFk85ve+pGUQ5nCbIAZ+as3+irQ93vw5r+nwbDOyD8bP2nQHNef4ufzyOCHAccs+1oe9f05Y2pfKYS/HaN4mqw7Xtgpry5Gf18AjHWWNZZZPAJ4bO/oCQimgF66aMgIpfNLcU4ARa6vFBgi05GDUk+WoUbZSXuC4nqlznTG7f0ND5d64O8maaS2p0QQ2WK+MaL6paQt9Eub96Zmm0iqtF6yTX0+fsF493s24qy87oKl4HZR/SYQnZ9C/CqixeuLGe/NDLD7hBT99pJi1/znA9mAXnL792h1WZkE4B6bwrjklkIykA2Cz8/KQ75PB08gHpk2puVEFStwc7hgRdWgOfV5z83EQcqoYA0qv5kA9TQj3nJ7SOU+1EzV/xAlSmfrz4A6DQL2RAvU7lxvE7kb1KyBzvm0OrDnHg6uOyF8omvpCuJm48482QcKJoqMX2pYaE53lHszmoJ0xe/WVNZkOthgIv3zPSlQCOYGOXTl3F3YDcCieI/r/ISEFeZcHWm07Rm/w9/t/OsTNAg7ttgrur0+WMZdme/i2UcgBlg0DOtwfuKo5LTT3shpItF66Yhdc7zNw00b3GBc8Bpk6ffByHI=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: airbnb
