apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: airbnb
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA/XY4qozrOuONUsdKMK3Eu+Zi5yh0DKAl6fyFB/DauUiczZ77ZFqoWzGDxE1y3Mvf8zGZNL2QAOU1t9FELR3RVPOoDQJzY2p8fZHQDtmuWiv92DyEaStR4xM/EwY7bvzlhmRY1O0VuZZxfd6h1+kOH7YFyqxHLeAhCDV03FZqX+lauVzrfZofK7VBvsjSmomsbbvy2yU+uXAu44gyve8IZGB809XxTMyHx8pTaOExpa82LMa/Nztm3Z+mGDGeeu6cNL3WLMkb77gZVFKMBuXN5aDqOEsS/vmRqvtVDeSyfj7l7YGGAB0pVo1WGOFE0rCYyeZ4ARHM7/syeu4njELuGECMfZKewhryqzTq2bIJcUJ32Jgazmea4q8Q/5BvXhPK84ziPEPwkaTRtYyOTf+STOyEvEj/ijqlpvJ0YL1Kh1AWFhkhBobHlhQtgwokz1fDHplAbRgi8S1N7RYzvXAjTti9XlJD/9UdbimBeFZ5s7o6jI5suU040HHmdhRhwOpUJ/C3j/bsiPeXrG7AxQ9mxqS0sdDvZ6EvJ6B3kSstGjNO6gzQyuK59JjXmIwKh03B4TK8nyrxxrW1qvGjVrU2mipVF60SPnyab9xaf74kQsV+xeMKr4nIZbhIYN82V577E/Pm4hFsxwTVlIvx4r0xWkEH+rmqLBhK7tuSOEX86RgoxAb/FkwsCX1NtHNqnk90Tsf7pxynMkA==
    POSTGRES_USER: AgBXabouJN2QL1AJlFAIOmYSRPiqBTxpjcHDK1PsB+rtkIYGFu/buxSShrT1XcEOz+gSFB2JXVbPINf8Fz+djxq+275kDP/+KSLF4FHzERMoK22j/eukgkgr5N4kM3LSHHre6MDXjhpnq4ImKr/gcUWBCvL88Z/W2lNUbhKoM/lzYnSOWY9pnRfPbtsa49QoTMindbb6hB7B5CaaYbCxAww5nU6FWIRhvOnmDqzkXrlOckHTP2EBJbtv6L2/uiLumqfn5Pdo/Pttt/6pDxp9x0KBSDAf2VzyL2shKvXjBokMbjsx5kb41VQk56KFpEnqQczH2EGuIErnKDElE1FjAcLLsxvmfLI/Bk/Ao/W2sPkeeGRQg8le/HkxOhQ5kn1O5oCrm560coWdRw1nrtCD32jICanxCTtFZEA2AO6Vxgt6UpFKNxVCv2tz4LWzvMRSB9LFEkPclf0z2u/eOIkgHntsGjKeOf8kzLrrbqOIak9VdOrMTHFBL8UkrADHw7B4J+Vxu58M4CKNYmfTmbHWwShJtWVBwE5/gPI1rKf9QfAhDUAK39dSj2HxlN8PF41iFexuvOYrJW1vEyLrYK7IT+BBMoIstC6L7M8jveJgCQRQcQOPjxFZDgTruq9/eOZX9f4xmBATbRUSh5tU5K5nwCD2ZbaRBBY1tS4fThThOo8zTnb1dLmy1uXH9PcVFSGu93cQ5DqLrj0=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: airbnb
    type: Opaque
