---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-coupon-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCmmJgc+p5WezIbdJaP1mn0GQNroLAYT5xgS8UjSIRPk7DgtM5azqqOMoAzQ2OBygEmcaji4Sb01pye00rdKioZGruBTveVkIXWVLEtZRE5u8qwZD4Nq2+y7vxROnGW+ker1eOGusUTWKhulmDw6UNDkaKX79VEuK929m2N4QWjVsOIbK1e5OedrOkAh0bkGrHHVMygzAeZHhLmPddQgqIuWg5sBBL+6OjBy+4qmvro3cp/v8/V66nAd+5bSz153VS6XF9nWQwTZYECRbkIPOVS5z9QqPqWF5B/JTMCgvVRH3Wx8a63kYvaTH3a5Wc/48k4foK0dhpTWYzW3Nmgvg84kIhEnmNdwLzPGLmKMARFoUW6ML1zLelNk0K7N0uArvsiR7eriwdEduZCHf/OuvyqnW8N+nOdTRk2vNuF7XkM9lJdvSlEUG7tGuCCYf8NcZfKxLtt2rn025HrxfcHIBXy1ssq317IYC43sYN/k+py8Me++GdMMD+vwRd8so1q7U8dDUsENXhEWIBV0S1GO2xybg1wLxMr0ioEOIgHFearmV9fW3W17ncDXvpHMYxTBSQPLqZ5kSNTq/q/7astOOcmrTwrHj/4enWKlIQ7VVkpnWRuD1H8Tq+LXG7iliRDfrXjBWO2PdaR54aerdJTXnPkzb/xNCVEkhTEVcp4pQ5tZaHopPMOvwGrhtpy+ZyrQCaCJyPVrbsatJdBcyEImKM5lY2mP/X1uolZbdVqFy1lYaZMynxdQ3IWt6xRpVh6uc6fsQT/L2haCgCacdb43dKB
  template:
    metadata:
      creationTimestamp: null
      name: service-coupon-secret
      namespace: airbnb
