apiVersion: v1
kind: ConfigMap
metadata:
  name: service-qa-config
  namespace: airbnb
data:
  SERVER_PORT: "8094"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_MONGODB_URI: "mongodb://mongo_user:CHANGE_ME@mongodb:27017/qa_db?authSource=admin"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: "CHANGE_ME"
