---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-qa-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCO5KUZaTN3S0FTni7W7O0nvJ0khiZqDWD7ergYU1YPRlE+q+h8qkiKPaUYvJd8zP+rmasGxcXWnSKV1kc2r11wCWjFb1EOdBF+DcgaxEHSl7X0hnkSoSkaUMDzTyv62eXz6e8YcZwPwREZOanLGyG3sliMyKdC8JAqCWqiNrS3YmqlQMceSFffWNENZeDUl7rxRjbgz5yJIG5arKLM+8znzlZLdI6nvt7wr8KDgVecdlSO3G85J2C/6Mp11Y4E51/UJb/dsFSwoiJUxZLZNj1Y3ePQeR0XjEEdxDQmRhKEHrOc4SEZ7GLWSgChhQYps+Xn1BFCxqAPa94N4fonx11ne9OOhvfeK/7Pk9uPKu4L1A7KHX9+/KxBHZD4IANNtNnBKZnhYtsIfB/47xCR0kosTm6lzcCE/WhMBrqd/er5rGXuVa3a4I85yjlAYS1ehlkC4s4Qvyj+sPzHQqFpN9hdrt8Qt8fxc6YQ4Qsiyxc+Diru8kSC32+ZdYSUSjH26kO4JUs9ld72q9J/mWS26LA9qPxvU3UpeS10o6tBhenGyucJ0P3MJlQT+5PPJBXyMRrJqIAoR0SYY5vzdMbRUw4lfIFNNcuLdk17c/ZVdTQr2ggJ/F3hVaRj7oN0toAXgNx5udi+EGY/flQmj8303+jVYjWCDlF1IwhGHGoSavtySIhVZBaVunUDKPwi2ZaQS9mOcBPmtpPIh+sxp0E9WUpKO4mWUTpbw/VMhk/v0t2zbSCVqEkBgulhGxkxZ11KPnDtnoY2tFx9Tju+NnaSMo4q
  template:
    metadata:
      creationTimestamp: null
      name: service-qa-secret
      namespace: airbnb
