apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-listing
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-listing
  template:
    metadata:
      labels:
        app: service-listing
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: service-listing
          image: ghcr.io/my-airbnb/service-listing:dev-ca82a2513c0928d09475c3674d7f033eec86b5c8
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-listing-config
            - secretRef:
                name: service-listing-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
