---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-listing-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgB784e0CuNv4heOgHxdrzO26axAdvtk6UIzI7YLkCbgqiCKYUufokaKks9XpAtcwnPCtqyYNcg8zTYW156YMtvjIoHm6R4gNJ6qcsBchJHMCD7CSgmKE/cUXy5dPawHptLcNYS2ljQTE6y2m+bj0xOpKTgkyExSgwcxyOL87mZe++Dm46eASQKaEaKfFxmJjLS0WT3CfgsxNYPw7HD/MC+HP+A0+Zb3+CDh/J1fuhqaX3Jjr/H7H4N9HDMydi6a35mu3nAlcUF8pRErs1yxBLcBCEB7d0qdHPNxF0JZLpw0pLpDftXr5l1Sfir54LPHUiX8i/2ng50yyDh12HYTle2NuP5fbYFBg3AJfwfNjapIneYzLMOxxv+KAK/RfqL3D6c+srGNrwsnXjkGx05MvKoN7kMj99s6xlPwEmkfyErHD8BBPF+KKaVlssWmOXeWQGLEVQFTAlUI73CEw6na0coPonlDY8UHyoSicA0Wc4XpAgQzGdF8RsKHUw8VxcjxCWa5TWfo/dl1Oj7oe1jj7MKDdqurl9KXn/C+kph1/valfCDPAW8Oz16g+JoZ5QNGb/eDqSvALsIJXwpKO6wNKY3aeATV92aadWM13BrjD+MVlaF/kHw9aEE3SStMlzez3NL0dIY/ud89Zq9kTZILyVx0RVpIUl9JtcE+3sVbmnoIjtqHeA7kkJK/ikCcmcBtJ7ihutjY+W6sbPbfQGyUsM8VKO3fRJvlzytEZVwX6gFyhEL7RFk8IRjuMsu7jA==
    SPRING_DATASOURCE_PASSWORD: AgBb7JJ0ZGXUvFWd0ekBP0JINEW+nVZoJosznZNap2NvIiPuGzzDjfzQjcDJwN2gLLQsuya2NmxHze1dbegPgS36XnfMpzdE2yq4Hs88mfOu5R4D3YHeHKWUoGqGbQy+kBEuMrhR6ncH8ZXqm0yJ4BX5oaMMFbEkwbjBoGQiuTzWg5EBk35ej/xEVAdyzmPZXHl7b0IQceH/rW4rbsNvsdWQc6TBefxLHjhmt84hln5bNqRfCyQz45MNW5sMDhjm87OERF24830B6UtimpyOP2GDjH6N+dSKEKl6gZSH1h13Hyskxw69mt2HqsRkIoze+gFHE2ZNqdhVng5ciTFzdqCgTi6NHidQmAXSCsJ7+LolPfNAFP04thqLCmfjf48kNxBM/t9KH21z0B9UXKOoRPl88JZJ3Fu51MIjUo13pkGAn4mBDBXHlyF1GZr7SKRkfR+566JPFM6Z2IPPU2Dop6rSOgiZMwtECqOjUJMv/lberzQI5yhlsiBV4rURK/0avODpXgD9xcNpWNRU8rI0COKcmwvV5WJdU5SnDzUtvMa7vRX+M3dMPI46AqJlrJ7N6qHr6L4aYt/OUsJla7atsC2GOzF+WjmwCbRfKSaQPYu/hg1hXYe2ZgDxbXH90zIfOVIr4PFoMvJVf3b5H3euCvs3ITh8mn2Ai6qmzoFoiog3aIZw8/RU4PEtUwTk+f3QnYINU5f5SuUQ5/s=
  template:
    metadata:
      creationTimestamp: null
      name: service-listing-secret
      namespace: airbnb
