# TEMPLATE - seal with kubeseal
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-listing-secret
  namespace: airbnb
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: <SEALED>
    JWT_SECRET: <SEALED>
