---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-listing-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgB5ndWeU4J9j31lG+40dsaC2xqPsUKUhyMT3EerxJQhPNVxkWR1mBkreEu0ozgpyTIWTGz4b6fmAZKYwd7aYuM0w7br9Qa8mcPeHiPvzUuHN/ozlTSVNAibJpS0KudSjv8N02TEgCSv7pWSFJ8KDBha2TpCIL5K0kwih09rGU7b8Nar1q+8fqC08PWUXPi/mggwvPf6YPUkPBJUl/7WlndPeQnvk/gl4vsoQhcikOPDdb9mT29NOSy6w2MapVC6zt6bBIdmsYwRgyfv9gkTRuEEZFnWrG8H3e7Jtoyxp/3utVK4ViejiY7eDW0omnCjjzkmHrKZkXUg65fRKiLg2+5Qda9ql8emfDIyyWrJyQiwv0b3McSIpR05oZEfBFrZUDv1tKe2oFHUik0C3L6Pavs+KTzG4+flSWsSAxf1e3/CKRkU+Cgk8Umvbo4WMas4dRLxAduc2/uL9RRT+R0ZkBT/k2Ti4LR4+8WtdYPeP4nfZbVIslKQTBvNcKse6pXCbXqATsVY2Szf1w3zhHfwNAIKig7iC/f4ZmZBEXUpknPcA7XzMtwM+mdQOaVks8F5flyGrqclcpv+mg7K9deoG6510r6eKd6Pnf3Gl/RA8TFQjPHGdeBBzGCa/QQR1XAVV7WWLXVW8VaWA0SxT16lkWVh/ItndErm+yzcsuPkJc/nCuZC7a7CXpSS94xr/IzNyQuPnjjHnNL9b9nwF+6khdXWtigyNLUhSCDCZraeQr8aU+MzuDPrEpxFCZoqd3FFBui6r9mA9twfIuRfu7JZ6HCk0fSJdd5qpUVXxAaSHe8Pb8JWDBDmk6c/OR8b+EMFa7R3zVnmiSfXmiVTwIAmA2aAfgwQYqrCPUEvbAhvzXDpig==
    SPRING_DATASOURCE_PASSWORD: AgBbMnOJ6OBtWnY30IM3LwaKb8AlvbRrn9uV9GV62DRyZJxtEb/9wGnvg6Dl5dLrbZ058MfYQl5ht1WEs5uxBnWjwlSk1K4ucs2h8xUzOqBuf0G2VQFuUFOlk2jSbQ6lD0LLBuEjIf3cxwpp3iV+i1RmtFqTsesk6VspwyxhghwoaKgNvl65JwsvPfA2KcwzFU+us1cXien67sIUOOdun7mCXxxUbOW3XhJudQsh6nix3fM0UGRpaHtMIbHef76wVcqPRWxml6jz9i1xCnraXxq2zHPFaDlIYMMPAva/BYZl3UXrcNpAy2HzJZbiB3G7zqbmaxMkpcRqRGL82TIb+QbsAx5xr87uygkwN/fabeouy82iuXKyQhUMhPjfULjYrdMhWSbPpa3a11/kfkuXhhE8/sJsrCImJ/QW8QSvYaocdUyYcmO1b+8vqpl/iTj7UELlOxzOgYpVFRpI/+fmHjj+kUUYplYejhSWI1TuoQJqU7XZpEXlm8kuO/UaMGZhfjetUidR8ugPzPfS1Qfj5jnsWzdf+qPsAQl8Q29CpE4If49+36KD6iv4V4LhdV5vN7Bm3yCyckHIOfwujRrp5Wpnus4GNC68gnpIxKRHI4SWUM1XEro793ZiedtfnYpuI7Qha+wVPmxWsosIhUM+sN731fOvaHj6AE6Wt6lr/xNXfa9fhxYIXSNueGaJNbofg8Qr67CjsJmUjA==
  template:
    metadata:
      creationTimestamp: null
      name: service-listing-secret
      namespace: airbnb
