apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notification
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-notification
  template:
    metadata:
      labels:
        app: service-notification
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: service-notification
          image: ghcr.io/my-airbnb/service-notification:dev-f26291445de62e3439e2b7452e5236d658891921
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: service-notification-config
            - secretRef:
                name: service-notification-secret
            - secretRef:
                name: rabbitmq-app-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          livenessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 25
            periodSeconds: 5
