---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-notification-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgBk5gXRLcMwZ6ftex9+MGKZQpippE9ZgczdFx+jATodyUvfpw+mg5TqXgLaXAaGgKrqxfa4TOjEioVmxDFmvd/x6AXJTZ0Cbs0iXLQhGzCsMJ/ILZZF0rCHh7D5DtatbXp8m8eB1++sXccOwqik5iJb8Uu3UWTEaYXEvTDt90b3X0nb8y/nB1J+8D8ZjYYo6m5EGMzwXtSK0a0Q48x3qjHBZjefyO6HjvqZrSvg0s9xH2NgSd46uLf0lpsmqwTvoT0vISU5U+SNjhazG6dKcmF/WnXDLv3unLq1+GmcAhA7XyuZe3J798V0qbNK3ywfCIXkNZp+JC8I/7Jn6aEdnI5kk0WJUGbMgjoeQtZcACggTepJ+VsvllsP37O6J9opi34DHGRCDAyVAQB8bOibS6gZwlB1kgaO24jF+vHbF45bBUHc/FSd7neBF8TYGf4e2QnT9yF/xMsKjxQpHW9Q7S9JSPeCHnXCDJFmhCEVufI1mIDt0o+2YIlVoWMiOlhy6f9F5GiI+FQ/hiV4oVP/AYVAVo3iYe3HHGwA71O+XJk/EXGqv8rchSzQmPNKnA2I2y+mZnwYPmAYdqaKNVopWnm3kLVgk4m2nduAS45SvVNd22hpOpKrYf93UWWB5WnZnIqIHg1gHMr1g0Mnjw9G6Lf1Ehc/CNsQBBnDgrrjJFm+ujf4FrSSfgrR9g55Njsrmo4qW+RgNZHw3O+fWYP/5oy+x3DGqIXJ6IM8R/20H2JWtBc/WJwNj7waSczMXcSa7p2ycKIEvoEh62xxb+aJVwU0w1KmzhYo4BJ8cfasTh0KuMG0oJlU/XWKCNel8e36u4ZYAD74nPrLD5EHkHXDUu1//nFdHxFMrVcA2UQjECFBVA==
  template:
    metadata:
      creationTimestamp: null
      name: service-notification-secret
      namespace: airbnb
