apiVersion: v1
kind: ConfigMap
metadata:
  name: data-seeder-config
  namespace: airbnb
data:
  AUTH_SERVICE_URL: "http://service-auth:8081/api/v1/auth"
  LISTING_SERVICE_URL: "http://service-listing:8082/api/v1/listings"
  REVIEW_SERVICE_URL: "http://service-review:8086/api/v1/reviews"
