apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-seeder
  namespace: airbnb
spec:
  imagePullSecrets:
  - name: ghcr-pull-secret
  replicas: 1
  selector:
    matchLabels:
      app: data-seeder
  template:
    metadata:
      labels:
        app: data-seeder
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: data-seeder
          image: ghcr.io/my-airbnb/data-seeder:dev-2a28dd6ef4af5a497feb3030669892cea1a89c83
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: data-seeder-config
            - secretRef:
                name: data-seeder-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
