---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-seeder-secret
  namespace: airbnb
spec:
  encryptedData:
    SEED_PASSWORD: AgBkQwg8RSRzEeNIoFZW2sPljE2dGypFzAKzVXVzTuKwissXyMiZQeLmoE9ZgJi9YgSILinxegnfZ9L4y5A7nl/peNTuVGWXH4xBKfndCgLq0tA4JrhYp7OjnNFu8kMLtjr7sVQPukGl6e9vXur5uWebaeJ/hZVy+gDqZWzi/nnKznSxwepShy2Sj9rkVF5QCgQ/6ra3BdemkBXxLrDVfe7cEhzKes3RlxUc7Lo8uLxHewfleRfMVUXS1reXiQ2AoZDr/ZY1VmV/bjgyY6P4p1bVwrojB3o1TR8FbEOpnxoenAo0NXGNh5RKLr9gzkNAgS82lMtslBt/KFKApHQckvocagoCSU5+twcAq1A6k++lV2Bmb8X5DL33GSMpR4q/8xhZjWYABXtQQK1rg1fqrVMaaiBUz4rZ2gN4vc1L3wQ8wAOofowm06jD5J6mCv/ksn1THwEhyzwzqnZFjm5kZgGshLSrv5TxeDSl4t08FVVM7TW95Ll288Cc8ONpsc4CQGa3L48Fqk1/lRxzvQ5xbimteT8knu6Qn6Ch6Lhj5q+yA3qnEyncXjbCsT1/NPjv25P4m1WS2b3wSyhS/1fTPwufx20epPqPAJVIMtPgEwv/1OHGB2c3DasSPu2fNg8CQQt0spjMmBioR311KOEqbwTBg25OB8UtXjsSsGRg4a89T/2fuRhW0jyWxgz+pDekadjRLseeIJddvEz/ss+Iau+AxcY/CX+EiHQccdwmqyiuEA==
    SUGGESTION_IMPORT_TOKEN: AgBJ3gKUYQ0eWh8/79RDHSGnPm2EjorhsI+CraR5mHVFCCrK6k7gCa6Ti6AG6eyRz6euY8e/ns79ByovdFLRS7Plku8zmnG3JIXXPiJ+zIBBGSKu8fp1VXycqPuQWU++VVeM7PsgCTL2zXg+7NIsexhP4+0nQCtZJt6e2YtVhQQT9vHD7+aa/jT3xWmUXkSnT2pGUUeMEgYICQw6ur9SMW0BRSEjWKdUdv3TjbjqIkjDzRJTq9TkLzrMwXNKHj3WAjq3NNEeNgczNaQtCU9zB0PPYTsZCl1GBwoeTcIpmIXrjY5MQAdzsjERsmPkT1gbaViGIVpwa+UYb25B7zg9ASoZ995P4HCkWCgiejorZNpX1/R1f9CoIM0zBRNQrfCvAd9PPi/6mTHxbelNKAMjJRNh6lV7VzzNeBYXX0iCzhfL7kTphJLAyLvGMkU3OcZ9Or54dLKFSuSPCOLUMAK4Vh/9Kt22fqeOEFgBFgO4O39wQKd1HMoSDmg6I8Uewc8MCeLA7aD7L42c6ZsEqQLXDHsJZ1GkZ9faDrkigDun1Ic6TdPrleqx5ZoE2q6mpNtqQXWBsxEcBYgP5Rm27Z3vzuQH73KzmVSPGj0Y8H5FscyT5crst8SBb9UblCKXSvonlFrzyf1BIpCrUKCVLnEUl/uQQY93dUxlAsdc6LLrV2ZuyYC5eH1qHjF9RkLBgp43xLilj3XsEYT7U2Fr80z8iG34SZOI8PuW/Fm7C5RxF89bXVDKB/aubIox3qlvt6DnkR4=
  template:
    metadata:
      creationTimestamp: null
      name: data-seeder-secret
      namespace: airbnb
