---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-seeder-secret
  namespace: airbnb
spec:
  encryptedData:
    SEED_PASSWORD: AgBtN2HtRwvut9nfGiufIoRKjJcwBokZJxvHe+Znm3oBLjZrnQ6Ck/QVIIGP8pWcLY+aR3mdA7Q50mKXBae4Or6+G3ToIg09T0iercIhA//ShgqVeR6dI8b7bmHwM9M6LrYOfMKZ7zGnfwrhkRaKga7L3UpSOzDXp5cKDOx43oHtpBC4a0vqqF3a81gpmSybOcfJjpVWx4jHVwAai3c7Xt92Lt9+e1a/Yc7IhnJ1yvCk/BxaZ6BoIolbJ1pXdo3JelVpoeMCDUZc0IRzGdjaMdcNDfjsYIFVwZOba9MoZDLrKBpSt12W61FeGHPhDYWgj5pqJk1JVDYqmQbXcEJ4/teM3OMsAP26Wh9RHSslgxbjbgpAtFHs6sTlhT25/Sszm+aqCQX0EDDZSuT33JBEPGgheIW4JaR+NDsv+J+ubANMsUZwuy+Z9ZRRUnkHirQABib355xBoP5WibyHQneJ07VpGqJ5jUFXhynS4F+ALLQeV9tGLm6MD0E2TsKeeQnMaxLtzhcgXrziG5YEDUNX+SEkYmkNYvTG3C1ftZcnpuGVHfbnyZaEQ9qsoNhby+uGToRHTtSSbP/ba5WqiZb/uUCphfEAHDXmVzCw4Nb2aZopZZ041+fziM/9CejG89vOwiDB+SO13Mpls8h3KIhrEr+Q3DCPBJdYaA+9teAm2WQp9KqzfgQJ3kRRFLtpWj2pOcj6hs6oObtm3iY=
  template:
    metadata:
      creationTimestamp: null
      name: data-seeder-secret
      namespace: airbnb
