---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-seeder-secret
  namespace: airbnb
spec:
  encryptedData:
    SEED_PASSWORD: AgBkQwg8RSRzEeNIoFZW2sPljE2dGypFzAKzVXVzTuKwissXyMiZQeLmoE9ZgJi9YgSILinxegnfZ9L4y5A7nl/peNTuVGWXH4xBKfndCgLq0tA4JrhYp7OjnNFu8kMLtjr7sVQPukGl6e9vXur5uWebaeJ/hZVy+gDqZWzi/nnKznSxwepShy2Sj9rkVF5QCgQ/6ra3BdemkBXxLrDVfe7cEhzKes3RlxUc7Lo8uLxHewfleRfMVUXS1reXiQ2AoZDr/ZY1VmV/bjgyY6P4p1bVwrojB3o1TR8FbEOpnxoenAo0NXGNh5RKLr9gzkNAgS82lMtslBt/KFKApHQckvocagoCSU5+twcAq1A6k++lV2Bmb8X5DL33GSMpR4q/8xhZjWYABXtQQK1rg1fqrVMaaiBUz4rZ2gN4vc1L3wQ8wAOofowm06jD5J6mCv/ksn1THwEhyzwzqnZFjm5kZgGshLSrv5TxeDSl4t08FVVM7TW95Ll288Cc8ONpsc4CQGa3L48Fqk1/lRxzvQ5xbimteT8knu6Qn6Ch6Lhj5q+yA3qnEyncXjbCsT1/NPjv25P4m1WS2b3wSyhS/1fTPwufx20epPqPAJVIMtPgEwv/1OHGB2c3DasSPu2fNg8CQQt0spjMmBioR311KOEqbwTBg25OB8UtXjsSsGRg4a89T/2fuRhW0jyWxgz+pDekadjRLseeIJddvEz/ss+Iau+AxcY/CX+EiHQccdwmqyiuEA==
  template:
    metadata:
      creationTimestamp: null
      name: data-seeder-secret
      namespace: airbnb
