apiVersion: v1
kind: ConfigMap
metadata:
  name: service-booking-config
  namespace: airbnb
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/airbnb_db"
  SPRING_DATASOURCE_USERNAME: "airbnb"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  JWT_SECRET_URL: "http://service-auth:8081"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: "CHANGE_ME"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "airbnb"
