---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-booking-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCYhGzKilr0eDNfIUTZQOdkPqN2FbhtThUZEcqPnwW/FDd8pNstxMwZRuC430HUVCPFMFr+haYT/N94RTXTt2Oi98c/P2Xn/m22lxvqohMk6QINWhnG26Bsz3LHVU87mSWOVbFBDQULVN7cpyt41JEpa64vVxJ9SqAmL1wHvqcbm9way0RJyyI/xrwy9JXh8yCvWXf43luM6b9OwaVgirCIiJHNIUUKVymyrQMKTTn3z4vSrwoK3pLjJSwxIBJ97xvWvNJAwG+0qlFf1qaPw9kIGTdUKwKcboL8xSXn6+N1te//Cq2bHZCwSKsfc+SOLXAdLuqtfua0TVLdC+oMd2Vd/XOBEntCbkLXLyWw4SrcQ/f/Nq/AZ0PbhH+2TgHpI5zVmHsUHAIA8C886PvJ4j2BmlMvRyG+4/d3rYeabIdgcDMwQO9RGMSfQGkeSyhlzdCkcEmrOR7cLLLvyhsOlzuMiJ0IITEqwxQcHeLtFsTEI6yhlYlXnt3eb14ZaGyQtztXWjXdBIj6DZoNmzUI8rKB6mClrRz/0hcE7VHmeteLC9xxczAQl2LUOAxSEyr0YspSAPNzTvISCI9IS+DPmZR/yfPyuO/zqs5dPERkTrDC1wI9WZrTysQTmg1RaTUL8lNPMLeBMSARCvj3zBVDYmEPO8AXo6Gr5TCGBzRPVCCb++ercoSKyd69Fi+lFcF7ndFGqE4GIOy2znazjb3/5y39aiqnx0Ay6E8e4TKURfU5Fc544eXwIp19xddnbw==
    SPRING_DATASOURCE_PASSWORD: AgA9rKCQ6TSIQ41tq5Wq6q/UJOsKX4db76NqEoseIrOWVvvZWVaWJNNzEN1yV+79zPJdn1sDS/emzmJdERYduydysVUF5kfiD+KN3DRHir3qjCnTywsN67xOsGLZaJPjfgGmrTk/OE4DYlB7GLthKrkafXxVs6n0lLmO7keup0IaYXSreUZxLgHl2qZ7IpFgPE1fFFRx8jxKtke28odfbhNf+tMfWgvszAbt7eFHmyzVHDFLWg7ensmfgsdBcBsSsIO5hDyE0PBW6uCI+WSfqlcI7ci67tEmYOEqzBAIOiEIYKWyDBnrgl5cnWTIbWuSjpq9YX1Z2/wcdUKrACjKb3pdzF8tkUUtb2uiFMlPhPgB+NGQYlNw4AebZ7KCD3iSR6e/+eXLNFTuMnVUTI0qtSSbtrorgbhL9SK8ixR9nsP85n9ovHp19Vo+0tWM+cNrdVn08NWXDInP9aszsfndPB2gbe0bVYbHveejOxedxsFZijoCDqIGjuNH29aMnS90OUff6+uGXL8BptMO1fhBlDBrQ/FtmhegTCZSuemMNy2JRWyQ/DK0mKKyve3COkOQ2/iZ/vG12P3SCNk/1DcxebA45sVF8h84qNvTKraNKTENhqHX7W2OVk1wjFAfmOkbAziGvfzOmiUWwdfH4d/QeBWoNeMhOZ6zSddDCqniuamXJHhtCGBBo9jCnMsM+71UY6jgskwJUVTvycY=
  template:
    metadata:
      creationTimestamp: null
      name: service-booking-secret
      namespace: airbnb
