---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-booking-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgB+eVgm5vJGEDFSk+gwW6JDwl5ot58CPOzr6Cak3AVWv+lC2TqLuRA9rMtthtWHbbqWCGijxMyRHv/UnoLivDlCAnfpl4ayX4EUMCYGLNOhbvBN4Bm/p7hIkb70of5X52eqMH96oYUwh7esYPnHLdRMQSVYj64YokRGX3RnZyNh9ne8/LECewXcXewWcjRS6rDR/RD4kLuKR+lgJ/xWBQ/Tpg/5CL9Rv4VYK+tIEbTAMnucEPrkW7qkfEGeCyWrLFkaRM1wvNRthyalT807SgNgnLPXVN/ljVYlmF2/iqSu+ph0wlxn0ffdEJTnUMrib0p5ux0keqy4UCzcX8VeL+pguUnq4cxrxjSYQZl8+5gOhIa+0PvnRwc2B3J+2/f/RUxmWiHsrTq6+qyzphA6inmN/XarClMCIB5gNzEtGsWZgjUz35Gwci2fOOeC4TARfCrtdCmTLLxihhrx8LdMFJZmsRgzwkYh7KZ9ZhFraVstnEKfwtD8iucQ4SsZrJlkcvENnTyFRMXKchRA3QplF9Mna5Lf7Vso10oOvs/XOm1tJnrTquqs9p8oSnO4/CNhEH2HKirQGVypVB0ieR+59VmpImh2uhHAro8h/r1XSf9Ah+F7ddkKk3IsWKi/1Uh4zJK1Fx3xtT1Eq3PkO5Y6TDnpfyi0zKHf2PdT3m06j7J5SgZCCpKBg+Y1AsVAb89ILjRWn2B6EOQ2vqszXPGJ2RIaMDF95fXxl0TQxfdFT++e6RoYxqVubjsXAlH98U5XnSuJmOpGjGX2ZYw8WQuoJFYLdST3TFWaFzAWKmqe7D55RvShegXO8S/O2msnNUjeDLDTQS1k52s9dzEdohjY+BoYR1o+xvQVGdeOSQfZZsuiPg==
    SPRING_DATASOURCE_PASSWORD: AgBdt617n9Vp1XnLcRes6ly2cZGbUhQlLfxn1x1Qb4DEzEytf3K3ETjtSRyqx4l0en9i3ORL5j3uoqLXva8BWy3y+Sjp91opRnY1jJFkliD4BUtW38NXY7pok9JZo68Q+MITuh/e/XzLvM7Yojrp6C7SQ5hh+FYHBx4VWCEiGnViW8hp3cTyXISPSH8Lqi4KZriIk+aReoGcZ1wz5GIUVCgomVKrrr58z6JR9ch5QrNrwicgreLSJ+Laxy7UiDpkd1NcxQbpDcblklNOM3Kkdfw2u0z9IGBP7qTyEmcxLalyg95w5yanwUayJGg5OnNRGJy5TcGYlkpgFb1bh3AwjPaK/Jxgxmp1MhfCDJD+Yqtf6gh13T9vm0G1i2OmCELQyj1s5iK0DYkEjNKmmjFWr1S2p3+cJaLkXaX7uDZqzeDkkaOLmGcW4Ddi/VfpM5EwXNs78En26fGAqa2JGJoOol1KV9vLq3F93LD1K/0Jj/H64xMSMoFYE3cN+3Eep4DzD02Ott/EYryP4ydIDI2sA9wQGFJmNbUFx7MbbN7jhPAkArab/U+XZ3Uu++dbG8H0h9PssjP2pBWaufAG+vVSmCg0BxyFMhYwc1u3KFAj+yazHTTnk9mMEqR1b7I1u1her1t4MBpbOjcM2+L0M05YNcnKR1+Sj/KuWgitfrMJ435IAKhW3kGKsNmn/cuKWm3c9m0faCqNgxA9LA==
  template:
    metadata:
      creationTimestamp: null
      name: service-booking-secret
      namespace: airbnb
