---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-concierge-secret
  namespace: airbnb
spec:
  encryptedData:
    GEMINI_API_KEY: AgB1xFNldCxbU5ThaHX4UyMDL1eG+gltiPADheH4DnBTW2Tkz1oy8nTqeJHQnEmlbwx6yEU0AJXFy/pKq32xc0MCfqoP1FZp8xoE3jmENyMhda+BjRjDQZYSxIY0hnMfIp0VVmkHJH+0CkFVhbNI4dOejMx9V5EQ+7Ybp9Qs3tblHI4cW/IlCvksbA2SVy4q3loXymI+OKtNZFjItZsNfbEzjGLDe/PuQGs65Ia5zrZpR9lv3dA7rmWqM5zDlcP16O1YSpP9BXbvzQIU7c4nqf6m+J1BwYZFSWK3TMpOEZYELN8rB7eS232e4aG+OxqNkmNSjTqX6uTr4VNOW8C4TTJH4ZrOWxUIxqT8vSsG9CrMWK5XUYEvaYjOWCAfskoVmL8KFz6qVtGe89UH2UifS4GB/PokgNn6xh7BNQvw6XN1XRl3RpWUVsTvJw/S9UJW/N2MlSDzmnhbWcQz+9Ny+m9A8MPik3oD2tmJ4RBvYEfJF4SBMuMB72+cm0cUOREeMvpPfeNYTvFuleKh5+aEQyYUNsysoPtdxYZBBY6pWo2dlCsHGFAsQ1qeqaP1Op7DD5T4AjHHA8O9mFYNQtdE9g0Jx4dc+nnqqA+2Ygz66PyzXg2kXH+2uUOQR8vNsQU4F8w7j8RJ11iKRXfE6lDuJ9YnfYH/PtiQlaN4PjQVcKNIqjjwfg3xpGUFQe6tBaa76Avod8JVJ8npbWvVs2a8M8NACqdycTwuVykX8F2YzuyLs56qKdw2dpco5fyhhP0/NEG7wSpYvQ==
  template:
    metadata:
      creationTimestamp: null
      name: service-concierge-secret
      namespace: airbnb
