apiVersion: v1
kind: ConfigMap
metadata:
  name: service-auth-config
  namespace: airbnb
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/auth_db"
  SPRING_DATASOURCE_USERNAME: "airbnb"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: "CHANGE_ME"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
