apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: service-auth
          image: ghcr.io/my-airbnb/service-auth:dev-e99a7ac0f0f100089ad354d4711468135f991279
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-auth-config
            - secretRef:
                name: service-auth-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
