---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-auth-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCbyph9d7YTzv4ziKo40evrTWP3jvlsGc7xt1JM5mVEqqnhAe1naJlT66TewH013zmaXv90pKJT+fyKXkwcIRc62Taowd56eGr+9XhwOIpIoVQsgJ4dSZ/8LG7L7eafM75BAr2zy6bUmFP2ng08P9ae8UI7lZCbbrWYGqXvkrjNRkUxEaklEpDh82apCVgPbWETvXnDW3tyXERujlCPpHRBZgaj6Nrlf60+jrI21UtuMZ4iPOwVLRiGVpANKBTZ4tE/FXD1LROAOZXtEPrHRdWo6n9KlD6WtptTr8bSgASQ/Yz/Mrqb4FAw4q+wkDps8CrYc4MvbgshcXkbdzyTJZMdtsxhZ/sysuPhYHLD1rg91IMngP0ia1nJ/ywc9Iu+bDyeDFZ5tuEcD6T6DLZvDvx3OjerPJstj0ixlnXkfGm+IqjDhBBJHn3bZH2UGLc/kgftB3hnMP8uu8tVcdG3n1t9T1KLVyfKxQe6hM9FrJM1tlqsGupwt1YXPIvQLqlN2EiIOiyU3EiINytrZNm3V9kc8reYBp5yH7R07tShIr/KeMhM5hDWUkDRSwL5oGzY8dwWiDIBfPSMVvGL4b0ZLkitL23445tQMvK5DZ8q4OH4lb81G8JhMINRbjOWLE+5aYqBKEhiAaymWnuAhjauWp0HWjnmmKquNDMh404hf1rP60SMglqUgjCRqiqCGtFdoHV2HCYTStAhXEkpuZCSsFiVwB02D6GBRRcxLrjc12r7Os9qjwe9oGgDTDsoDw==
    SPRING_DATASOURCE_PASSWORD: AgAmIIdSAa4tWcxKEkyhu7wU7ce/h0z50w2JF04UueRLAEO5fSVsF3nCtBDg7GT+ZS90pie2djGLHDGnDt7af7Ddth7VdRkAP3Fk6lcBIxY/CtQbz6lsD6brEq9x5Mob+je2mEc/uiIc+cg1+3Md020FaEGvD/DEfhRBkmajIhw68s+b+oI9q/yJDmeAzVHMo53rhsIk7gfOTzXQphwG0l7PVkEBsUWZw/viE/pySjd/oJtXX0MIp7mUOaC5NW2GKDll6yO1CkfbkqRBlC/AIGMm/PkgnILRS/bB942GKMpfqSTa1rFzfAujMV1nqbdoZ3d2nKmI3WwuRdOdwLpRwJzS/yNyUbyVt/O8Ow3S637tLirYJNhNevx4mJPbqQcurcMlF6L1TShy68bar1yfaSKZTUCZm132gPnftMW8U7WNp0vQsxkaIyAvONxDPkP6A2XrH5vrMD0zEMBR8CSiGmTCwjB8Hne1t73roPGSAcFEyrX9m+f1NdubldsZ2Km9vQibuJp+LpeEDUXZMfp38+NzW3YWqye8G5KTnjZUN2flkRs/6j6xb4UcaQN+/P4loUUz2midmsChJJLTCCw37Zdb+n1+oIw5qwrf6mPZz8Ew2qbg62Kvb9rtDv0TT6EHxxjBz1hgOingfHedfMfYggH+xO2t/Sb0oUe4ERg/ulAaQWN0MsZO1llGMZralUIXjNHIJbdrYMTEZj8=
  template:
    metadata:
      creationTimestamp: null
      name: service-auth-secret
      namespace: airbnb
