---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-auth-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCHNZ9HVcvR/wUGjvpDtcW3oHYZUJxZNSUg7zhGBXNUPOSIuxJV0BLPNwitwV+cymq37Vm3YCut8SpLRNS9P4orhK83pbJzkluIA6HAOJiO07DK29nlqoUVKzLLJsNnLccevlHX+lLPQIZbRGAzs8eh4vWCoZx9fhb5TPE0BzcrH8mVie9Fgx0lZzkJDbTfaJLHFeccN1sfONeCNLnqzZUKX/8DXwmvVMFmOgBa3twV2Ju3hhqoJPlM0ntpV+on5HS+YO149POtyRN2VmjDSAFhAm8GyVZvk1IwDBHCQIV39VzGYVNh3fOPOuSDivhbtuBqDg+LBRDcMBsoBUAbJnig8V0dhXAB0foKpil41SgXbXhetWVdfauGcuq5FyxQtdtxOjF35khmP5Q7jUyb0s7SPqfmw1lSyxpbbBXHx41WmoLvZJthGUPIwheUR2y+BDohTWBfntpZR3zGbT7Q1qCI+Yqnc0LWKwUZAwu2ODyq0ZNxGoskzaPcLfBrqXJSPoDKsyX2ixfq+sWHgK4xmN9vLks26QT7G+zC61RPXTA4yfY4wn/NM/fD6fz8cHMdmxBv1fH14mLJwCb2wZzFFW3UoVwp4rN2KG5x4N+VULaYDEe3KYfcGAD8NJkFHsCaXkuANtSLqYdV3l3GNwcJw3PfzzT7DPvWZT2wAA7p7qqenPa2Km/uxiom3mrcGIEDstgx9y6iHpONV2OriU0ba45ULdejS6DmDMoSg1+Vm+g6H1NsFeaeFQI/+Hofx9ZErhIv5ocSl8Z3g3OOtQGddxVT6xi8unD32/i0akEUhVw6zs3ypl9tlIGXmpQHL2PmmyEJ4FOofM3+NmfWphot8k7DziyNGNFSEsegsFrbLlb9lw==
    SPRING_DATASOURCE_PASSWORD: AgAPliwQVILbiwHuzz7TtHAyKM3Gr5PmkvKOg2Ay5fDZ6T628KXJ/KoBoxOOHdIDPScx1KWer9VdK0xVQYurtTwwFOVX7BinXlg8R8UBU5EioDyRNeE7g4wgLQxNVMhx2afvNPYmDHO9iAvu0WX6t0FOwqcJtPtbzPk3Nism6av11RauhwSv0o8sFByJ9LcgMNiuWlrzwDTgI9SYAmubtmYjfxHJxNsYLjvglLHWKbOmylzuIXGO7+B0UuzYsLaX/ZiyHwXgKsCzMeMIHq5GkX7fBF+ld4aoKiJ9LmR2+WGVlgpKHyRwJL+elAEWh3w1H+xjLX1bZHadyAuoIqknp2gM8ZtknKlela8AAMz0a62rRastQezYc9PuxPjGhqkgnuQollrRwkIfKM0OofdQa9S7Zzb2UFXScmPu+3NnKz2hSooaRvhQWv1RKAGqq4s2dH95tiGPlthNY/4JuT4nevF57WJMG43l79yhNcKCzz4u1nj4t/LPSRnyOeMHEpgNsZ/84WW5ohHBJwUF8wzKLDXgPhrVHL0m1TOuEd/whRY+NF1z2gtVXovHkfDkw4obKbF2RLXqInFRrKWB1SS5DjXFG7aTHiMDNgXjHtWKNTQ4CO3VQKH4GOJTzaew9fDc4H503fFKYB3GtPNROiJbE6Mx4OHIhabw7DDZYIJEXdIrirleNB9T7XKnWgrerxfk7JqcHepcqlCSRg==
  template:
    metadata:
      creationTimestamp: null
      name: service-auth-secret
      namespace: airbnb
