apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-chat
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-chat
  template:
    metadata:
      labels:
        app: service-chat
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: service-chat
          image: ghcr.io/my-airbnb/service-chat:dev-ee804b59e666c85061ae2605a41604dbc942412b
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-chat-config
            - secretRef:
                name: service-chat-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
