---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-chat-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgAClbQ/ZF5sevg2Yl+oyHs+O0Yx889TZUhvPcrX0g9fyy5nMWD+UWT7vFaKdEqOw5xPlE9c9ihTX9QMRET8gg3DBvJyE8m6w2mFjJsX3nYHqMOZFeF4nXHKUneEU9Ka6bXfMV0kyFnlMnaySWYyuipCAmVDrDJqfxRnwzbmpBg23nqNjguDyIJlop1IVrZaH6tE3gqr6phz9AE0Yci8JuW3QYkOHymMemrCWLEcZ5IRR1I3eQYAwLEIyo4esO2yNw2syJUt8Iq1niTloCdxYlxMjPnMjnVPhEy2WT24IHQThBFcX29HfETIj+1rW9ZhT/mI349lu2DQzxPM3Q81tcuWqbkWXYTAtGpQfMuHCkQZ75VGyFWxCxZR9F+M/5NsePNAJ+j5Bkdjm2Nn7MOc+4lxbQCpUaIYu/lO5LO5vx7H1Ak/dqKBe4Xx6JhsjNBJWwqxNTbAA1++86R5hUwoEsR+yYs3XDATVtZ5zELcEnl0DSqBv/JlsN9Y2tPzun11XT4JDA0SLao5n0mvoYSAdqcfEa3yAp3Og7fjbhOxPRUwffUTfsB+chFqMNMer/Aim1zyqriWy/jnbO8bZfTZSBHq35HPrqF/TKC9PczfQ/2LsT2QC2mEJ1EVov/inMAFdvfSNpuHY5qwNubQ2/HRCwWR2xcF9SZ9JveL4GnvcJ5JtPZs+z3V7X/iHAdlLHQSef87SxW4+MTgd1nVvP8boMljRkNRM+fulfCnzAG0sKPM3gsWFBNBDlFrK6CKBATHTNA/31U1gUzv+ITBfKAr8mdkT0z0UltM4R2ph68yQByeYz3cpV0YH9Ihkp+wFlINysuuBj1sF0KIpGkW7eYsF+IutXEdYM5gbRiHJylhAXyYNw==
    SPRING_DATASOURCE_PASSWORD: AgAk6OROzJNvjTnVx+Oi7ZtaZs/HdMaAA0QJ+Q1lsYJWHFUmlu1nbytFUkMD6/Op3w6JSXCGaI+NNnon3v0OXz24l+R5MpNsTxmlzsQz++kk8oqX++h0MCxBrHwVtiHus10yEs/qBaWAlIpGOxfMsplpWMq7T+nQgsdszG/qSk+zD27itSZ1QsCiQC1tliXmIcwHL1bsAOSsNyakcQ1R7Qrquf2EHdXNzIftfoifXQKYY0QcyVWQ11FTAXX30zA2Mx63y6w7OIhlXd87vmnFeBB4mZv1RtJ5dA/dae6OZdZF8MM2v+4FnhV7fVARO1xG5jkYrvhMI8eTe+svDOfpqg4DLWpUTZHsK4V0hhQ08VUTZetoSwas6jZ5b71sLpb5hFI0tCptpUqBChKgGL/nNtAa9IIS872ujYu6T2j7NHXMkrhYhATV4O85Dnh9kk3ETCTpVUJUynQELxx7Dq5WPE+1FQAaiaVq7J1+wCGwddhR9MbIcUzPDz09gGWVbv/19v4Dyloz5AmqLrTjooQcHdfVSBugqZjgXxVF6rLiXSpgowcHM/Jw8uhcSnFAJlw1/xUpahvoN6egpdRSiI5w/B1U0KFqZvFm1fj33SGhsWlePl+Gq0Yns6G/CHAhZo2oeSo2y1p2gwJQEFMUkky2oGAKwWm+Pdf/eoXcrbpSU50hdFCqyUY5is1JZ//cKZfzUaXOfjc+Y9w0ww==
  template:
    metadata:
      creationTimestamp: null
      name: service-chat-secret
      namespace: airbnb
