---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-chat-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgAPgili/B/lmlHNt9qJZmuJV8SMvhFakVwU89244zNJYJvI+rQoQw/TmCkHBpMzExD9lF3OmYP1tROZ65QX47pS58jhW07wvyKtW/55U+ILhLNH/vVr8S5SGMMRVv/mQ3EnBHjAE2ghCcyxB1vF/zWci1zIz+yGKAWPoodxdPHfrJCT0NDovkWLGN+2rjrUlBZngegpPL1B35Pkf0pEyHr3ouD5AL0gSt1nqQ3N+OkbClshp9957BZeTs3Hiqv9OuVoUQsAWlNoXte/ec6UvBczNO9vijmsbKRn7pESma990PmJ52VVL4pRZpY+QqOC4Prrat9hmRM08KchBojbzYEWLIyNWqbQZ2Hjqmu6bPnbmNptfxh6BiU71EK5ywXx1r1XTJtkue9RNJoXY6ktHzAitdPLdUSkjzUbxcZPN4Cm9QVdIQJQwEtC4KJMkG3283so37xtYm3plbFrqOs8aKvYo4DLvBabkbCaw8fxtNazEX8Qm8HmC1n7N9Yq/QSZf+IujLDaViLON9Hoa+seLE7fWzPXBRU3SzMUC6iM9RgVg1S9QDPS9Vx16mjapgACUDHJ+xPffVaJyA68JLdv7cD3bjspWQQAOUGLQP2W05aNw+RHgmSe7wKu4wic8MrwGyuIwKuMsLlzag+cOLvq9v50HQcAGWeKfG8AGr8wN4YyQGj3NUFca6d0zrT0aSAaT01MYKmecbZKEwgkRMIhu0pxEhEg5qej544t2UGOUYUxeluVplfwSyt8eQgNIw==
    SPRING_DATASOURCE_PASSWORD: AgCFO96nA49AM1AHOBCarg0cKgP1irLhH3CkhTHinPnDJzTAJxBI6cXzOjj4ham+Xb0aREP7LPtK7JC8IpncQJWtgw78Lw+C0nth9cHwY11CHsJgKCw5J35ZtwvLiqBeHYYKQL750JygNLAMBwJqi/C+wPg8jY/LC3puTOiEX9g3HLT+1PK4J2uPRV929+F4X0n9yM4l+5JQrjmljKXKgu+YYTUH9mE42yjonBHIz1XfBXNlTzfpxH/Tl7NyyGFIEqyKMQukm/Nfo/HMY5U0G+Yq1/SAsiqVay5itnqpYP1bnxaRFJkGLni2kUDNPcAJgVWHvPYgXu3GTQwn/Tj5DkG8DSivvejrw7YPI6/wcBY0qX3Q2GkfrpKYD7Uc3SJMtGwS1lSc8VvLKr1ZgfExk5gVb9xhiJl8IuYpfCK6gi/UjLBCtXxC42OMLCmNCTs10jRKTQ5HfbpIsAlkN8Vb8byUjNrvm/lnVITXN79sf2cHnCZGGHhj4hnQmVa7yNzzmjY+ehmKVLooglRTFEA3Cj70QV2OdILpW3/6btUdhDx3PlECYF1JOupzKrpy7sDLXPqYmAO/n1qkXW/jOEYlBxLo1sId3K/ftKAxGKmkoPLNaGYMoPy4EieZo7UnQTGOUpp/AaofpIjyE6Gr9qtSkTcdWMAn9bAeVQ4v+LZEj8bvT2i52eag1RYZPMY3tCIqJ5irNycN94gOmHY=
  template:
    metadata:
      creationTimestamp: null
      name: service-chat-secret
      namespace: airbnb
