---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: airbnb
spec:
  encryptedData:
    .dockerconfigjson: AgCaowFjdF+Y97gHLil2hOfXl7nuLuCCmeYqPF+xRU6/hlwgxywfDfRE1YarD9lhSj1uWI0/NIXh+/IJZpkffJfQ/oFPE2YkYsSbYw+oX79U8Ly3QDAEn6BhGDgzZe0EGg5nAP+bseTlUYarLmBgLfDvdJdlBGRaTnsBGcdKCj0s/n+mIHlzAU9Fd7OSf0M/uHoqnZlWEiErbbbrSwxjDYtlWJ2aFOmZtRsJz7OGfRvAEMjTEEJ4OBfLMH2KuCMyK5/WvU7yolJq9kcbFX6odyMHwesV1DRc0z8xaaGnjKKWWdNg4UJyEvYwznFZUTyhQH2ggkEvglpPMQB3REBl+zoKw1Zpsoou0D6ITXP4boOBVy8T1cTDkxlLAXDf5u+hQCrrvKwt3RXLc3JeuwcMrkW5mLw3i8a4HwCS4dCznBzZQg1N5LOawqbKx3bGvEtSnWW19xasgrwKhho0I3MwSmOj79vG+gHc0c/z+uWnt1o1d2myuw3r3RLih2OgWNXhfVhD1stoO7Wu6CBc4i386E2dZc8YuTjn5IRGjukOPcm0nHjNbLh4qqTtOgaKqRhXjb8xYLBWyaNglmSK8oRuDjojgJbbiE3Rio8H7ML76EcTuRb1brsL7pw9ukRCxzRbmXRN9BVKACviWcJMtqHgLMlQ6ZY0NjhYB623ePc9TVK/R758/sMz7PxKxaVhNr1WAkhknHNCWJ0PAHBs0TTBD/VRgz0EMXirmbcr1ZCHIZ3npSD1sy0N2A42wVVn2DskaIE/TlU/ZfNi9xduG0Z/HkidiHWYUAsu2sBx6BHYwUWsSI6i1PxDbrllV57yXYq8pHlr9qCyXvThjjIczgow7CqBVLUi3sxo6x5x+YKi4HBDhby4gCZGPlvxftCwjtXI1f4cio+uBPvqM97HrlrVXdLHyh4m/sHTU2F3EeQlLviv2u3rm4JabtpKup4=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: airbnb
    type: kubernetes.io/dockerconfigjson
