---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: airbnb
spec:
  encryptedData:
    .dockerconfigjson: AgCOPtj+x97xj6CS7mJvEc5EOQJML2a3+SUhSf5jUL5bTKAmqp5uA1yLh2gJyp1GWA5Ks4B2BDA8qY8QBSSGVRRB1n7vj233GfWxqZnlisjlwKN753q/9laMM7v2OEbXJ8LqFVQpbciMYpQtCqzNSUeYKSorBtV+LDt+x76sb8OM9DySq2PpkVCNMB/ihKYF8h7HKIeluLOAvzk5f0be16fpg3s2kN4Mka+ATkJlCUdtD2E57d1h9IGGAOsHnx47wJ3zfK5lfjPMXEISY7GKx541xwld6ESFAkSChhxDvMV+1QAIRyRb3vFYrTR0cAslWOs/kw6aG37/4ZwkgkkbqOLgPpMN1ByP3Gr5m4hyoD5skEgAR3lRtPzxaKAWS5bdKobFvLywyDb5xET+2VDlTzmc41FFqnx6IckYrIbAd/cW/fQacSnGxs+jIPbGmab6zVbF6aWEDNl5dUj/7ehoBU3OGt/jKT56wwET3Vdtq54tAXBBsAWC+nGhfx7HnxXmU4Gdtu+LpgZdIOCPUqin2Ak/7YtfqYt2LYGz0tFqLJWgME75ZAPNW+Qi10lC+l+Y61Akwd/dwLWzWsqk5kffHJBNrcz8VYHMq/57UGkV8CaMpfLTkAFTWJbbYtZJWqvAHw9F2vjdD9lrIsi/xjJcR4q+mTZX6tbmgYgi3LfFaHjf3mN92pEmw2AaAA2E6ovuhmNps5aGlVwa+QAwEV19vMMwDRswUQY7j7BBrXLomZsma81U5swfcjMp7wOP+zJzL7zUSFcmOYrC7FJ+YNkZ4Y0tdoYHlBKEtKM6vFGvJwy0ZjCXg7G5ux7dadBFFAF1+RW0iOKtiWB5dyc8fxMf4+U6nNrFzxdZt1pmhADVBwRE7RFb30FyILwWeq6mbv51dD3WQJmvZgvyyxvEOmWKKhRPOgRxn6jmr+i+R4czesLSIivqltYrE4W7Dr4=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: airbnb
    type: kubernetes.io/dockerconfigjson
