---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: airbnb
spec:
  encryptedData:
    .dockerconfigjson: AgCjctTVYn0xKe/IfpFZMPpVTTu0FABy6NmCOa4EyS03dASyVobRi/PBmmF/Q11Y/m4zpzKDXRjPouqn26t0chdxuvoYfR/l0/ZIWh7KsC76UZx1VJIGGQDg7+PlYItjK/H4ddPSdn/bYAZf1wafz38CwKFNUKdzz0DcC8O/Et6mZNpChLj1XtQ9KhoDGbZbBVzp4yjq3CuzPF4az+/i4av/fPLwMTF+lqeAA5KHFaOQGNEzyc4En/dsqVEFghN1/N20NRivKCdjcw+eERcUWCBs+TJP+Rnh6Kchq3rZpwOoWLo/9SBrst50gaLgqXKGYRPbFH6ftCx+KwxpV6aBKs7xwjkmZMMIo/4GcrodHGSB8QqeFsc7G5/UTRyhrbw03MhUWiSP0Z9RvHQDnKQB8HyVH9o6Ga02yjPWnEcBn3vBfqymL30lSOYygZolumDBI3CEKIQG5VcHNH3e1LccoSHXSPe+TFhPkaWnHiGFEx1wsQLYjn7oeXz6c1Ap3azotbwEMtA8iVDMrcFW7zdK28SCCM9CS88ztXKNjiwpbkqABacFJ81lslSO97djUQuIhDK4Yqk6nw6U4a2IQx7pC8UofyMxgHwPA3gGz1GDa5X9lq79Eaw6wEjTNw8YPCimC7/3wq0o9DUa9xnDvqzQHeZZpuA/c1XdHmTkR1mJMMOTcOlwtQELsn2v9vyH/wst708aMXwTukvO6JsajIwO/so+f6060241Zc0VzHBAxq7qHimpdoxctGSiu12AsngDhyhr8xYaq60RNb5eVwa3xsS0rLhfhXvA2u73/5fVdZlLosFd2QByU+fMZRcSf7wXjiD6/pkJkSvjyxduVshLFnE8lskuM2GnGML297KXjpzmJqBm3kFzX1XKMxHopmC6W9GsAuNXrUpzfEgIW2r8pcJE531JfjLkd1NeYlNV3IkCSjTDhlNPUPayP7A=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: airbnb
    type: kubernetes.io/dockerconfigjson
