---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: airbnb
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgBQeXxfb7g3ASS1RgQfDmujdYCKV5Dc2/xiP/MQweGOfJo7PbecEzAsgNfPOVI3Jpiz5+nGZ9Sy4eeo/5//zQg/I2dxatklzVKrL9ZLDAheqn1B4+XsFoGs+kHJZ7xmhPJ8wmR7xt661a98qyggX+v6qFlPxYo6/J/BXWn6YJv/H02lPNSAIukZTZrR+lTmG9a+w0ei16mqJq9Sj4GmPCQWXb1A7lE+svwKnw6+it0UNLBV4uMOMD3QUN2Oonh/VS1kgBmLwN2fFobG+ZHEU9CPIKzMhgUP479MaD7doPjZbkfoUPxFwe9860Sfz2oRe4vr0PnltWA18mNmzdrDMIHgta/7Cs2JQZzugXuQZbCNfeEtfvEYN54stDPPd+fMeVF4Q0Z9d3yAA0lKx6fXpMj2KH3RgTpZgECE6Gq7xvrVjZzHALFh0N5N4sJb9p8AO5/iCIUIUGB2WWGDtHppbc24F4Oavq5ZHoYlrzBMukxZ/1LjIIXNMZ7erTxzg18Ymtxe6Iz3gAQPtyyanbLnkc3SCXvlTF8PtV04agcP1pKV6XXqLFd+WGhei90YEsMz7lWDI4zGJ5aqEp9M40Q4m0naDCaKQS164C0l5OXB8gjPnVsZCCofErP0iJ0M5B3C8lkW7YOc1W9Pld8VGeFdwizSRPesN1cLpBpqI03+GodOkfh9v61Kf5TanJnAuWJUBZxmwKc+M0KZ82ImsaVaJ/KWWA==
    RABBITMQ_DEFAULT_USER: AgBGkYauPV5pde76f7zo+LvctkIT0AWYlwM7JhapJpYzGac4RdgolEjJYVX5rfKkqD9AjbIPudBo+3XLqV+9YJ9B9v+aSSHKd4qV2rOODA266G3BPcrd1KxqH3sYu/nqHIMLXQB4uVfaTsbHapksGCjktYYpVMoQ+BtY2ktVo0UcvdG8epWkUvQPmoklcNhWWC9XKTxJG40PwH4+hwDn3S8NeaTIbHVqhbOoqHrDmwwpnKjqj/CaoXjFwRJf44G8rEu49oparvs5me3zmbwn2ImwstXkdzKfnou8xLWqUBo0+RLYWeFHrk22veTCT+x0cKTgEwEC4EPop97BtDKm7Tn8OQDydoBuYMvP2MDWhMYxt7+UhGi61ikLlQSa+b9gdr+F0HuFYV43zxUAEM5rbT43nBj/2LqvxdSQHifKKD3AzMR5mvti+X+wKlz9sMeiii7zQdaVPje5+KAPVHZDFZFpaLHwajBW6coY8+ZDb/FCR0DacR9XHlflpU2ATm9zcWzaYoGJPdZ4YfmTkmkmI+YRoUNADhafRecyjNGIMEZUYNWdLsJlip6EQ5rOrWvk188/A7coryHyMkNSMYmModZKlIF8jtTqh2MlusIX6tIGFgyN7VhQDHTIbWvMnd19oEx+dmhX0x2R4gbWqm37/n/5B4HoN/LngBWpFHl5cBBFIEK+tMUqNZh3afhLXwPgG3w3/Wz3JLo=
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: airbnb
