---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-app-secret
  namespace: airbnb
spec:
  encryptedData:
    SPRING_RABBITMQ_PASSWORD: AgA2m8txBwrnZxmKHNycuDtb5rrgRUB5x8vSlrPPv2AisA9fk5AWQvyztrnsfkHVOb9uUhiEOCVsg3M8VEJBDE+8PEzcAVnjjdYSTuBJlT1wQBhyvd7YiLAQRXJPTl7vejz5NhPnzMYPlimkcnFlaY/7N0N2YaD68PBtHM/CB90Uc9LDaTndGvLlGxJrT/j64VkIAgy/ww/FH4Cxw2XgLTs1TYrXMVlQ88sjUAXwDC/2dr6ODxvUqSMRjaJn2xJumdDcsMslsVJO89usiG/Bk84se0FXsmKpsY8QLF9C0AgkluF+3IIlEoF278M0vWSYjkymSPCZrjkQ4+iq/PuVKUd9LHPdFVxPwSmJXB4NY+kDYMDp60YNQfvEwmDqsjpwZWWwmEwS4D/HXYKcDl0yjFp7hpvRWdYGSrwwCXVCyM6PDiKb0FfDPfwe+7MsbsNwaMw8TJblB+FiuzRsPOp1wkyaXB7foHYh6AoJmZ6CTTGzNu1xFAm58dj0G8cjAYiXlPYuXLWHq049I6vMWILs61ApluX11D4Nf2pinhd1rCAWxMqMjR3HWDaCv0W8jH5S+4vVeCaxYeY4hRlcgeaTE+rsBu98HdjmlYe+BwABWXBXDwUwRr+YwuUyK3RH3fkzLrubPDoKTPt3CnKsxs58+3boc+jIUFNIJU9k/RPMKC5Z1LORxvTakgcdnbMMq8tSAlxPHUH2ZoXH4dwYThsOa9F/XQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-app-secret
      namespace: airbnb
