---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-recently-viewed-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgBnwnyLtmaFgKXtPwb1KjfbYRG2phSIbruUfPtrzLfiwPcsKM6Is7pF6CveQpfD4oAMvpZNOjhK4cCdR79Yma3wrv2Tdy7qank8sLLB9glMXxyXmsrApm6Y3qHQyzG05hDp7t/e9uHsX8T6UHsmZngrxZK7UhaS/WKSBviG5+cj3dVz5y6eFTwJ3KRHyrtAT3/ZF+Qqp2k77pOVwR4MYd6UU+X/n9psIyxqBPhH6PbmW6CU0MXoeT8d/G5Z76BilJIwR/XkPt+v3GoJrTTtrOhErLZ8ZfFQUu0wCQUIGcuabVNXrw54txXClKQnjpNKeBxR06v+l4Jl5G7Z6aSx/me76seL5aRRNzACYNgPG2m+kupP3XImNdiTTsn3nJyQ280qT20pGPtv+8trhEYtxOucAiC6gaUaI0IXYcOaGIKIGQu++Pin436GdaHbsSRYrT3gnBK1qewwoBs3S7Ki5hXQFziNp+Vj609BjhH0eAlFdrbe2ycROLFkN3pyHqlZFnOxzKzV15tpns8Dv4FHzzA9JmKgNbERjFxz90eTXssB65II9Yj3AwWmfL3DsHVB4Wp1658ZbHmn809GmG9pYnFJHHlHbdvpBfFKHAnjLBXdeM+qARwschQc1wA9vosnQkW1igHQ0sn3MfX1sp127GKixm5nNWz7AN56LgGb16f5vla5xhLmJUU5y/PSsezOs2FTP609yzWTuiSppLAQp87B5XHenpVNLLB0FBwZZRWlG4qvTsxJmPebUTl6t8RD0md0kNDxDgVtyTWs0SC2QzVmRfbySwHMFq30Nu0z8y89ywH33bEwIqSumV9G742bMGNGAWVbow2aLIvwvN1Z8+HSARtUNLgBX9F1V4ckkDbugA==
  template:
    metadata:
      creationTimestamp: null
      name: service-recently-viewed-secret
      namespace: airbnb
