---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-availability-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgCfMuX4x6fL5IovgyEc5C0ZW+5ZbmSXZDP4ykDSR2OSSEXd91rmqlgR2kzxe6y8D1Fw/wv6BmU4vlXv5VmslkCThw6sNbM97e7hkc5uvhN0stFNO2z7j7gbWdWgkePEXRcLZBAS7S0GEz+D+GI6BZErDTVlQtzOD7pGVemhAkBSoeUztz5qyQ6wkOVK220SOOv7jegSvbHSEOpGgsL5iNGWRMUIr64uDnbWCGo9Pln/trcGETqkt7rC7V7NpBRopi9igayMY9mh2UYQWmN6Ko2aWCwdPDS1N3kIqcSAJVB2r+/6FmxJo+OTH7Lo4sIC1P9d/bYvW+szIgpW6B0Al3f90CHQid+/Z6y/pXXHDgMhz3t+bJv7IYG4Hv1VR5x9ojiHpoSRogjQJEEoaDlvRsdL8rcTLeq7VSOb2rZFlcNih7Bj4cy7Wju93+vJ3QhrTQXomsCDLFS9j2Ppgt8v8tXJZghJTRhQiec5Or3Pu3/3wirBrb+NGvguJ5bWNmmF3y2MJ32iJWgi09GpB0tx1tcBJp7b9CvBCMmR6jNthjOwuEDdkq3F2dcW4EQasEfP+nNTvG5Oyg7uKdqaw+S5bkHpAzIsrTsBYlspFx0g5uDHgRjnZWRaFH+dH3DqFjz9+OIRMzA0BX9TQ0vuiv51GKsBXilUcdQJ9bnrPGHPI9M/Bpilxc1ZlIZrQnHpWLsI7b8UcD+p0RHyFGphRLtxeLg01fScmvW2j90ZwWM1d6heXP0vrKrmWZc0EJh+FOoumEvSOQQYP5aXP4GHlmCCCAFXytVVIke/ich9dDPOKHS90M6mBnWwhFE453I0OIVRd4tl7qd4VJtlcFgWsa9bL7q567s4fdRcK4zLkwJwUZLCXA==
  template:
    metadata:
      creationTimestamp: null
      name: service-availability-secret
      namespace: airbnb
