apiVersion: v1
kind: Service
metadata:
  name: service-availability
  namespace: airbnb
spec:
  selector:
    app: service-availability
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
