apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-review
  namespace: airbnb
spec:
  replicas: 0
  selector:
    matchLabels:
      app: service-review
  template:
    metadata:
      labels:
        app: service-review
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: service-review
          image: ghcr.io/my-airbnb/service-review:dev-ab6ef68d91e84e47629c72b87cc4df414e035b38
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-review-config
            - secretRef:
                name: service-review-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
