---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-review-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgB+x2YJ3QoW5XcoxycGUrWM/bFZ+w9q3WQ4/oOHSAkonGgR4Hqc/FjQPCNUKc8WnvaYm/IkeNr10y9gKsoZZkB9vm69PAuwD0uSRdcgCFDDerTcTRbmIftRBsZ8xpMtGkksb0/p+hLEi9WMLy+HPXouPgsSvydhic6I9Fr/pZGeT80zmYnwbYJz14fkwaGiYqyn+ANQkjyCn9lnCLJBFXZ2uzGslx19+krDchu6qSQ8wNtyJT25KtPromQMP94UeNK/7BvnvVL/2OlxLId7/tLcZbTSuxn7EO1q/0gAj4H1+jiu4ntDFmV+fsDo3fndUEALbV4qTV8Eazh5FyI7ke+dGULe9BdN71wmcFJ057Ry1N+mc73pwlIX3qKPyWwrAunsOVMgC/+/t9yUFvAlvActw0UYOd15wVO/YRi97XzHhH861mCC1M0xsBwWytxdoFddLdwkOR8hJJv7vPOF1fyTRn2ovmU5CPTjjIukM1gaAIhCj+vB00bp+IW6KwRA0tQTVsFgxoXBO14RTPtbc7K95DY3AQfsET2j+8sortJ9omNvn3ABD1VMw9F8UbkMuqJePzImGNl3+gTGCySQ8teq7t8KOUCLdGAXKpIIkXn2ij4VRUARlnUgwYMOjgnZEaX3PtFTJWbFH0BkBoA7qXuuF6EWlnlOA0OLR57KPWpXjwZ1Ilhe4OkocI5R5xMPinV6jLec2dmniCtug9p5nsvPThnfzmkG/ubgGrvAlcHesMpFFR1+0A/2qwvpPw==
    SPRING_DATASOURCE_PASSWORD: AgAtyv/zxRL2CyU6Y+j3MyL3jn5nm0UVJGz5T7uOnVyXXhkIvqVtcx44Mq9vxOIAxy3tizL7l3f1YCZ3zUK/AZDpdeMZrFHtUfwOKPUo4nzndxypiol0QbmaKX0RBktxTaHNS68RxrVHC6v23kTHW8dsDLQkm+juKkB0elVyWEoHbOyo8n0ZkC/7wntq1WGVcenC8ewZvTYs3oPl6xISWiNr/a97FnIzzGXBymA2MwO51P/ZkNMvYtLAjn+iPLLQ/r+cCNJdKR9cx+qzHidKsYpTjpnGwkT1lPW8VA+vfoiVzgiLM8k0y0W2eAhf5UdqxSv89HXv71E3ODAvW6NbtfZ6aIsSkZZs6seenH4GVnMpVqFQgCgUN3eAY77jFWtNvr6lPmIkzi/I2Qrlr/NBV3UsGGRKknqdj5FJpzRx9W+9SQxDSZeJH80zxHqW5uM7UR8s48nqTwLqbDeKPKuRUmu7Dty21ZtIpeadhxBy1Uctq2vwxBGq0pQyeLT0DnlO83YYR7aH0b7Fmk04hUsDDRCdH9/jFG5UjmYKyVV4EhF+5Jid1rr2pc54M14xYWIDDufGkGelabq79SQ3A+uLdppCaOCOP48wRx3mw/MS96m6Sin4kOgmkNm4YEDIH4iTkRBwkFoCy5UpgSrsE2MFoqfUrmgdd4ZlE8wDs61dBvU1L6vzy8qsnYGcFIp4q7Jb3e1srwg4p2Yzt00=
  template:
    metadata:
      creationTimestamp: null
      name: service-review-secret
      namespace: airbnb
