---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-review-secret
  namespace: airbnb
spec:
  encryptedData:
    JWT_SECRET: AgAZE5M+unNHIGcFEM1RHl5IwFEBY4lqs+awwf+eAeFhW3NZIaEsZUYRB7Bc5q8vOtrDJk3ttFmBCQEFCfiLMTTpSVDxIW9tt90trGI/AHN1Q+M+fCQRAcVQ+yINK+Ly7d7xKIpjGMHVMi3RJDikt0ISVki0ZaxEJDX7ap2wOeDHOv1zXnZw3Kbtv73xF/fgUgKYAZ5T4TEpqWgPp1rI2xA2YhWVcSfRKWRPzlNk8v22EcuIauyVWmFH4XpQHf4O2IZmgDpU623B227Vv6cVZ2EExphdpVfRKpejuVOcHY6jegAbnsOuUUqLiGkhDtMgplPAGDV5591ILNYDz1Wdy/aUXD+2vdk6UOGU2ex48a+V3pHCG2yOimsdBOL9TPUH8bDSJ1YrR6IySDByJqA6RyGi2I1ukz5w+CFrpT1mQj40MycnF9DDbtBpXsM1RS9eQ0QpJ3BLCI+cRbQttQg11Yd784pjLmwUf5k7ukhJTHqsffCyEe0qFw8W0krbCiFkBadWNtbRmTSeevjwYY7tze2OTfca9lZ3tZHUgyLoEgmY6tFjmPWOpJwkSC3RBbMEdBzHPYTR9rUStRe9RCqe/3sC2XFeNC2AmAArWbUYQTFBgvIUmfO71RqNEwOE4dETE+NJkJBHfDv0Qh06I74eWHmesBIfOPTagtMH1yEJldU2aoRi4MPhaB5pRd+lJ4QdNKyrp3p5djynYDwgMrgm/ZmllzO8MJ25l4CGqrQX08cshlI8oGQxrIASCLODwpOSu2QTGFgXXP4pL+EbxzCjgKVIrwxtfBTRY9IFnUrSsREoJoyvFZPJgMCnU+RF6KMNdrUCgfKKld1a6+1fVpb+K336pBWCntsLS4CDrQUYrSwYxg==
    SPRING_DATASOURCE_PASSWORD: AgB/fyVCGN9ZOcbkjE+w6ziV/+BFTdZzAkL0Qw0fWvPfmFMNZVJoF/qPQDzi1UNALXoB0LQF8INHXb/nNY46EgfTE+yQ/651aPgzoEOyJI4Dbc4cYrg7OVbcWq0pEz7RVU90zK5YHDnvGXINBQphmCmdRt28egZ1YFRBjez0HcKsyPWWC3NRh7a9NashJp0YyD9uR63a2XHtAnFgpiD/lDKi2PHAOhlDkYRKocxNr5HK/lcA6Z1GsYb3h5Fv0l8WGz7NE2425alS9n8N/2P/q/E9pb7dgh2YyVc8OVYUAfkDOU41HAWoCCRfEn+cGRq/FvBQCXTW4MBT8cXz4z9QnJftPkaFsawWEleHNSq6p+5z6YVKMMs1h/y5iurFa8tIwXdKUi3jLrq6xZLaA0qhF+NNbNZ6rcyJ1XtuT8bACBHp5FZWBkA5mh912c4/WABnjFCvfnGBexTxDPivQkVnzXcA4d2P27I9eCchovCPelZ4xlygHoBplVBKIkrhTH9BKsRkRG7HovIGS79theF2QtCMvfIwFJg+tnpv1MK2sHoiFaz/OoxlQKMG7rYRbZb6uwBW+AyP9UyBV+0zkeOdiB93VTq/8dmerIK+Y2p6gvS2Pn86/PZ7ix8RiPoK6eqjGIVIsqMy5GKmWvdXMHTcojy9qR3oXlUrHpxSlG0Evj2ubja9950vYh8IL7Wba2Z9uPNyGTu/xoEe3w==
  template:
    metadata:
      creationTimestamp: null
      name: service-review-secret
      namespace: airbnb
